---

- name: creates directory
  file: 
    path: ~/backend
    state: directory

- name: Extract the zipped artifact
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/backend/

- name: Install npm dependencies
  command: npm install
  args:
    chdir: ~/
    creates: ~/node_modules/

- name: Stop default pm2 service
  command: pm2 stop default

- name: Start npm service
  command: pm2 start npm -f ./main.js -- run start 
  args:
    cwd: ~/backend/ # maybe i need to start npm in /opt/backend/src/main.ts 