---

- name: Copy the artifact file to the EC2 instance
  synchronize:
    src: "~/project/artifact.tar.gz"
    dest: /tmp/
    remote_src: yes

- name: Extract the zipped artifact
  unarchive:
    src: "/tmp/artifact.tar.gz"
    dest: /opt/
    remote_src: yes 

- name: Install npm dependencies
  command: npm install
  args:
    chdir: /opt/backend
    creates: /opt/backend/node_modules

- name: Stop default pm2 service
  command: pm2 stop default

- name: Start npm service
  command: pm2 start npm -- start
  args:
    cwd: /opt/backend