---

- name: creates directory
  file: 
    path: ~/backend
    state: directory

- name: Extract the zipped artifact
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/backend/

- name: Install npm dependencies
  command: npm install
  args:
    chdir: ~/backend/
    creates: ~/backend/node_modules/

- name: Start npm service
  shell: |
    pm2 start ~/backend/src/main.ts -f 