defaults: &defaults
  docker: 
    - image: circleci/node:13.8.0

version: 2.1

commands:
  destory_environment:
    steps: 
      - run: 
          name: Destroy environment 
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:7}

jobs: 
  build-frontend:
    <<: *defaults
    steps:
      - checkout
      - run: 
          name: frontend build
          command: |
            cd frontend
            npm install
            npm run build

  build-backend:
    <<: *defaults
    steps:
      - checkout
      - run: 
          name: backend build
          command: |
            cd backend
            npm install
            npm run build


workflows:
  default:
    jobs:
      - build-frontend
      - build-backend